coppuccino {
  coverage {
    minimumCoverage = 0.98
  }
}

dependencies {
  api("com.auth0:java-jwt:[4.5.2, 5.0.0)")

  constraints {
    // Transitive dependency of com.auth0:java-jwt:4.6.1
    api("com.fasterxml.jackson.core:jackson-core:2.22.3") {
      because "Fixes High Severity vulnerabilities"
    }
    api("com.fasterxml.jackson.core:jackson-databind:2.22.3") {
      because "Fixes High Severity vulnerabilities"
    }
  }
}
