name: "\U0001F4A5 Security Report"
description: Create a new ticket for a security issue.
title: "[SECURITY] - <title>"
labels: [
  "CVE"
]
assignees:
  - mxenabled/infosec
  - mxenabled/path
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: jdk
    attributes:
      label: "JDK Distro and Version"
      description: Please enter the JDK distribution and version you are use (output of "java -version")
      placeholder: ex. openjdk version "1.8.0_272"
    validations:
      required: true
  - type: input
    id: sdk_version
    attributes:
      label: "Path SDK Version"
      description: Please enter the Path SDK version
      placeholder: ex. 1.1.0
    validations:
      required: true
  - type: input
    id: cve
    attributes:
      label: Existing CVE
      description: Please provide the CVE, if available
      placeholder: ex. CVE-2020-36518
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: Provide details about the security issue, including code snippets (if applicable)
    validations:
      required: false
