# ---------------------------------------------------------------
# workflow: build
#
# Perform on all push and pull_request events.
# Steps will be skipped if there are no build-affecting changes
#
# * Builds all artifacts
# * Runs all tests
# * Runs all code checks and linters
# * Checks dependencies for required new versions
# * Checks dependencies for vulnerabilities
#
# See: https://github.com/dorny/paths-filter
#
on:
  workflow_run:
    workflows: [ commits ]
    types: [ completed ]

name: build

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for worflow_run workflows to succeed
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/src_filters.yml

  validate:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for worflow_run workflows to succeed
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate dependencies
        run: ./gradlew vogueReport

  scan:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for worflow_run workflows to succeed
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Scan dependencies
        run: ./gradlew dependencyCheckAnalyze --info

  build:
    needs: [changes, validate, scan]
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for worflow_run workflows to succeed
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build
        run: ./gradlew build
