# ---------------------------------------------------------------
# workflow: build
#
# Perform on all push and pull_request events.
# Steps will be skipped if there are no build-affecting changes
#
# * Checks all commits for compliance with conventional commit formatting
# * Builds all artifacts
# * Runs all tests
# * Runs all code checks and linters
# * Checks dependencies for required new versions
# * Checks dependencies for vulnerabilities
#
# See: https://github.com/dorny/paths-filter
#
on:
  push:

name: ci

permissions:
  contents: read

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gentleseal/action-conventional-commits@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-commit-types: >
            [
              "build",
              "chore",
              "docs",
              "feat",
              "fix",
              "perf",
              "refactor",
              "revert",
              "style",
              "test"
            ]

  changes:
    if: ${{ !startsWith(github.ref, 'refs/heads/release-please--') }}
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/src_filters.yml

  validate:
    needs: [commits, changes]
    if: ${{ needs.changes.outputs.src == 'true' && !startsWith(github.ref, 'refs/heads/release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate dependencies
        run: ./gradlew vogueReport

  scan:
    needs: [commits, changes]
    if: ${{ needs.changes.outputs.src == 'true' && !startsWith(github.ref, 'refs/heads/release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Scan dependencies
        run: ./gradlew dependencyCheckAnalyze --info

  build:
    needs: [commits, changes]
    if: ${{ needs.changes.outputs.src == 'true' && !startsWith(github.ref, 'refs/heads/release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build
        run: ./gradlew build

  # ---------------------------------------------------------------
  # job: release
  #
  # Perform after commits and build successfully complete on "master"
  #
  # * Creates and maintains "release PR"
  # * Creates release when the "release PR" is merged to "master"
  #
  # See: https://github.com/google-github-actions/release-please-action
  # See: https://github.com/googleapis/release-please
  #
  release:
    needs: [build, validate, scan]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.5.0
        with:
          include-v-in-tag: false
          release-type: simple
          extra-files: |
            build.gradle
            README.md
