on:
  push:
  workflow_dispatch:
    inputs:
      force:
        default: false
        description: Force all steps (ignore changes)
        required: false
        type: boolean

name: ci

jobs:
  ci:
    permissions: read-all
    uses: mxenabled/path-tools/.github/workflows/ci.yml@master
    with:
      force: ${{ inputs.force != '' && inputs.force }}
