# ---------------------------------------------------------------
# workflow: commits
#
# Perform on all push events
#
# Checks all commits for compliance with conventional commit formatting
#
on:
  push:

name: commits

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gentleseal/action-conventional-commits@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-commit-types: >
            [
              "build",
              "chore",
              "docs",
              "feat",
              "fix",
              "perf",
              "refactor",
              "revert",
              "style",
              "test"
            ]
